{
 "title": "Fan speed",
 "description": "The speed of the different fans present in the electrolyzer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Electrolyte Cooler Fan Speed (F103A_in_rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"F103A_in_rpm\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "Air Circulation Fan Speed (F104B_in_rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"F104B_in_rpm\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "Electronic Compartment Cooling Fan Speed (F108C_in_rpm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"F108C_in_rpm\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "Air Circulation Fan Speed (F104B_in_rpm)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"F104B_in_rpm\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  }
 ]
}