{
 "title": "Pressure",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "PT105 Water Inlet Pressure (in bar)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"PT105_in_bar\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "PT101A Inner Hydrogen Pressure (in bar)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"PT101A_in_bar\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "PT101C Outer Hydrogen Pressure (in bar)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"PT101C_in_bar\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "PT105",
   "type": "gauge",
   "description": "Water Inlet Pressure (in bar)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"PT105_in_bar\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "PT101A",
   "type": "gauge",
   "description": "Inner Hydrogen Pressure (in bar)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"PT101A_in_bar\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "PT101C",
   "type": "gauge",
   "description": "Outer Hydrogen Pressure (in bar)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"PT101C_in_bar\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  }
 ]
}