{
 "title": "Temperature",
 "description": "Temperature of different elements present in the electrolyzer",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Electrolyte Temperature (TT102A_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"TT102A_in_c\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "Downstream Temperature (TT106_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"TT106_in_c\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "Board Temperature (BOARD_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"BOARD_in_c\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  },
  {
   "title": "Safety Board Temperature (TE108_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "\n        from(bucket: \"DHBW\")\n            |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n            |> filter(fn: (r) => r[\"_field\"] == \"TE108_in_c\")\n            |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n            |> yield(name: \"last\")\n    "
    }
   ]
  }
 ]
}