{
 "title": "Boolean",
 "description": "Contains the electrolyzer boolean sensors",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "High Electrolyte Level Switch LSH102B_in",
   "type": "timeseries",
   "description": "On = Electrolyte level over sensor; Off = Electrolyte level below sensor.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "LSH102B_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Very High Electrolyte Level Switch LSHH102A_in",
   "type": "timeseries",
   "description": "On = Electrolyte level over sensor; Off = Electrolyte level below sensor.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "LSHH102A_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low Electrolyte Level Switch LSL102D_in",
   "type": "timeseries",
   "description": "On = Electrolyte level over sensor; Off = Electrolyte level below sensor.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "LSL102D_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Medium Electrolyte Level Switch LSM102C_in",
   "type": "timeseries",
   "description": "On = Electrolyte level over sensor; Off = Electrolyte level below sensor.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "LSM102C_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Electrolyte Tank High Pressure Switch PSH102_in",
   "type": "timeseries",
   "description": "On = Pressure is too high; Off = Pressure is normal.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "PSH102_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Electronic Compartment High Temperature Switch TSH108_in",
   "type": "timeseries",
   "description": "1 = Temperature is too high. 0 = Temperature is normal.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "TSH108_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis Water Presence Switch WPS104_in",
   "type": "timeseries",
   "description": "1 = Water is present on input; 0 = No water input.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "WPS104_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dry Contact",
   "type": "timeseries",
   "description": "1 = OK (Closed); 0 = NOT OK (Opened)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "DRYCONTACT_in{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}