{
 "title": "Pressure",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "PT105 Water Inlet Pressure (in bar)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "PT105_in_bar{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT101A Inner Hydrogen Pressure (in bar)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "PT101A_in_bar{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT101C Outer Hydrogen Pressure (in bar)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "PT101C_in_bar{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT105",
   "type": "gauge",
   "description": "Water Inlet Pressure (in bar)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PT105_in_bar{job=\"pushgateway\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "PT101A",
   "type": "gauge",
   "description": "Inner Hydrogen Pressure (in bar)",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PT101A_in_bar{job=\"pushgateway\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "PT101C",
   "type": "gauge",
   "description": "Outer Hydrogen Pressure (in bar)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "PT101C_in_bar{job=\"pushgateway\"}",
     "legendFormat": " "
    }
   ]
  }
 ]
}