{
 "title": "Temperature",
 "description": "Temperature of different elements present in the electrolyzer",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Electrolyte Temperature (TT102A_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "TT102A_in_c{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream Temperature (TT106_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "TT106_in_c{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Board Temperature (BOARD_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "BOARD_in_c{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Safety Board Temperature (TE108_in_c)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "TE108_in_c{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}